// Real coordinates of the edges of the background image
const TOP_LEFT = { lat: 55.4519667, lon: -5.720025 };
const BOTTOM_RIGHT = { lat: 55.4172861, lon: -5.656125 };
// Launch position (not exactly the center)
const CENTER = [55.43539, -5.68593];

const IMAGE_WIDTH   = 8192;
const IMAGE_HEIGHT  = 7812;
// Max z index generated by VIPS using the command:
// vips dzsave map.jpg tile --layout google --suffix .jpg[Q=85] --tile-size 256
const MAX_VIPS_ZOOM = 5;

const latScale = IMAGE_HEIGHT / (BOTTOM_RIGHT.lat - TOP_LEFT.lat);
const lonScale = IMAGE_WIDTH  / (BOTTOM_RIGHT.lon - TOP_LEFT.lon);

// Higher Lat = pixels closer to top
function LLtoPx(lat, lon) {
    const y = latScale * (lat - TOP_LEFT.lat);
    const x = lonScale * (lon - TOP_LEFT.lon);
    return [-y, x];
}

const mapBounds = [
    [-IMAGE_HEIGHT, 0],
    [0, IMAGE_WIDTH]
];

const map = L.map('map', {
    crs: L.CRS.Simple,
    // Zoom 0 is VIPS z=5 (closest tile)
    // Zoom -MAX_VIPS_ZOOM is VIPS z=0 (furthest tile)
    minZoom: -MAX_VIPS_ZOOM,
    // Allow zoom further than closest VIPS tile
    maxZoom: 3,
    // Prevent from going outside the map
    maxBounds: mapBounds,
    maxBoundsViscosity: 1.0
});

map.setView(
    LLtoPx(CENTER[0], CENTER[1]),
    0 // Zoom level
);

map.whenReady(function () {
    map.setMinZoom(
        map.getBoundsZoom(mapBounds, true)
    );
});

L.tileLayer('./map/tile/{z}/{y}/{x}.jpg', {
    noWrap: true,
    minZoom: -MAX_VIPS_ZOOM,
    // Prevents requesting any tiles smaller than generated
    maxNativeZoom: 0,
    zoomOffset: MAX_VIPS_ZOOM,
    bounds: mapBounds,
    errorTileUrl: './map/blank.png'
}).addTo(map);

// Scale for reference
// TODO: Figure out how to make it work properly (it's close enough for now)
L.control.scale({imperial: false}).addTo(map);


